import { useState } from "react";
import { CreditCard, Landmark, Loader2, ShieldCheck, X } from "lucide-react";

const loadRazorpay = () => new Promise((resolve) => { if (window.Razorpay) return resolve(true); const script=document.createElement("script");script.src="https://checkout.razorpay.com/v1/checkout.js";script.onload=()=>resolve(true);script.onerror=()=>resolve(false);document.body.appendChild(script); });

export default function PaymentCheckout({ packageId, packageName, amount, onClose, onSuccess }) {
  const [coupon, setCoupon] = useState(""); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(false);
  const pay = async () => { setLoading(true);setMessage(""); try { const response=await fetch("/api/payments/order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({package_id:packageId,amount:Number(amount),coupon:coupon.trim()})});const order=await response.json();if(!response.ok) throw new Error(order.detail||"Could not create payment order.");if(!await loadRazorpay()) throw new Error("Could not load secure payment checkout.");new window.Razorpay({key:order.key,amount:order.amount,currency:"INR",name:"Ken Academy",description:packageName,order_id:order.order_id,theme:{color:"#B82A20"},method:{upi:true,netbanking:true,card:true,wallet:true},handler:async (payment)=>{try {const verify=await fetch("/api/payments/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...payment,package_id:packageId})});if(!verify.ok) throw new Error("Payment verification failed.");onSuccess();}catch(err){setMessage(err.message);}},modal:{ondismiss:()=>setLoading(false)}}).open(); } catch(err) { setMessage(err.message); } finally {setLoading(false);} };
  return <div className="fixed inset-0 z-[90] bg-black/50 grid place-items-center p-4"><div className="card w-full max-w-md p-6 relative"><button onClick={onClose} className="absolute right-4 top-4 text-ink-muted"><X/></button><div className="w-11 h-11 rounded-xl bg-brand-50 text-brand-700 grid place-items-center"><ShieldCheck size={22}/></div><h2 className="text-xl font-extrabold text-ink mt-4">Unlock {packageName}</h2><p className="text-sm text-ink-muted mt-1">Secure payment powered by Razorpay.</p><div className="my-5 rounded-xl bg-slate-50 p-4 flex justify-between"><span className="text-sm text-ink-muted">Full mock-test package</span><b className="text-lg text-ink">₹{amount}</b></div><label className="text-sm font-semibold text-ink-soft">Coupon code (optional)<input className="input mt-1.5 uppercase" value={coupon} onChange={e=>setCoupon(e.target.value)} placeholder="BANK20"/></label>{message&&<p className="mt-3 text-sm text-rose-600">{message}</p>}<button disabled={loading} onClick={pay} className="btn-primary w-full mt-5 py-3">{loading?<Loader2 className="animate-spin" size={17}/>:<CreditCard size={17}/>}Pay securely with UPI / Netbanking</button><div className="flex gap-4 justify-center mt-4 text-xs text-ink-muted"><span className="flex gap-1 items-center"><CreditCard size={13}/>UPI</span><span className="flex gap-1 items-center"><Landmark size={13}/>Netbanking</span></div></div></div>;
}
