import { useState } from "react";
import { Building2, KeyRound, Landmark, Mail, Save, ShieldCheck, Smartphone } from "lucide-react";
import PageHeader from "../../components/PageHeader.jsx";
import { useAuth } from "../../auth.jsx";
import { useApp } from "../../store.jsx";

export default function AdminAccountPage() {
  const { user, requestReset, isFirebaseConfigured } = useAuth();
  const { pushToast } = useApp();
  const [details, setDetails] = useState(() => { try { return JSON.parse(localStorage.getItem("ken_admin_payment_display")) || { businessName:"Ken Academy", upiId:"" }; } catch { return { businessName:"Ken Academy",upiId:"" }; } });
  const [sending, setSending] = useState(false);
  const save = () => { localStorage.setItem("ken_admin_payment_display", JSON.stringify(details)); pushToast("Public payment display details saved."); };
  const reset = async () => { if (!user?.email) return pushToast("Sign in with an email-based administrator account to reset its password."); setSending(true);try { await requestReset({email:user.email}); pushToast("Secure password reset link sent to your admin email."); } catch { pushToast("Unable to send a reset link. Check Firebase Email/Password configuration."); } finally { setSending(false); } };
  return <><PageHeader icon={<ShieldCheck size={22}/>} title="Admin Profile & Payments" subtitle="Securely manage your administrator account and payment configuration."/>
    <div className="grid xl:grid-cols-[1fr_1fr] gap-6"><section className="card p-6"><div className="flex items-center gap-3 mb-5"><span className="w-10 h-10 rounded-xl grid place-items-center bg-brand-50 text-brand-700"><Mail size={19}/></span><div><h3 className="font-bold text-ink">Administrator account</h3><p className="text-sm text-ink-muted">{user?.email || user?.phone || "Administrator"}</p></div></div><div className="rounded-xl bg-slate-50 border border-slate-100 p-4 text-sm text-ink-muted"><p className="font-semibold text-ink mb-1">Password security</p>Passwords are never shown or stored by this website. Use Firebase’s secure email reset flow to change an email-password administrator account.</div><button onClick={reset} disabled={sending || !isFirebaseConfigured} className="btn-primary mt-5 py-2.5 px-4"><KeyRound size={16}/>{sending?"Sending reset link...":"Send password reset link"}</button>{!isFirebaseConfigured&&<p className="text-xs text-amber-700 mt-3">Configure Firebase Authentication to enable secure administrator password resets.</p>}</section>
      <section className="card p-6"><div className="flex items-center gap-3 mb-5"><span className="w-10 h-10 rounded-xl grid place-items-center bg-brand-50 text-brand-700"><Smartphone size={19}/></span><div><h3 className="font-bold text-ink">Public UPI display details</h3><p className="text-sm text-ink-muted">Optional details shown to your team, not used for Razorpay checkout.</p></div></div><div className="space-y-4"><label className="text-sm font-semibold text-ink-soft">Business / beneficiary name<input className="input mt-1.5" value={details.businessName} onChange={e=>setDetails({...details,businessName:e.target.value})}/></label><label className="text-sm font-semibold text-ink-soft">UPI ID (optional)<input className="input mt-1.5" placeholder="kenacademy@bank" value={details.upiId} onChange={e=>setDetails({...details,upiId:e.target.value})}/></label><button onClick={save} className="btn-primary py-2.5 px-4"><Save size={16}/>Save public UPI ID</button></div></section>
      <section className="card p-6 xl:col-span-2"><div className="flex gap-3"><span className="w-10 h-10 shrink-0 rounded-xl grid place-items-center bg-emerald-50 text-emerald-700"><Landmark size={19}/></span><div><h3 className="font-bold text-ink">Netbanking and settlement bank details</h3><p className="text-sm text-ink-muted mt-1">Do not enter netbanking usernames, passwords, PINs, bank account numbers, or OTPs in this website. Razorpay securely handles UPI and netbanking during checkout. Add or change your business settlement bank account only in the <b>Razorpay Dashboard → Account & Settings → Bank Accounts</b>.</p><div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900"><Building2 size={15} className="inline mr-1"/>Your Razorpay key ID and secret stay on the backend server in <code>backend/.env</code>; never paste them into this page or the frontend.</div></div></div></section>
    </div></>;
}
